version: '3.1'
services:
  mysql:
    container_name: forever-mysql
    image: mysql:8.0.27
    restart: always
    environment:
      - MYSQL_DATABASE=forever
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--skip-character-set-client-handshake",
        "--lower_case_table_names=1",
        "--max_connections=2048",
        "--wait_timeout=3600"
      ]
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-proot", "-e", "SELECT 1;"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "13306:3306"
    volumes:
      - /home/ubuntu/db/data:/var/lib/mysql
      - /home/ubuntu/db/config:/etc/mysql/conf.d
      - /home/ubuntu/db/init:/docker-entrypoint-initdb.d
    networks: #사용할 네트워크 지정
      - forever-network
  backend:
    image : minjukwak/yoyakssok-dev:latest
    container_name: forever-app
    restart: always
    env_file:
      - ./BE/.env
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://forever-mysql:3306/forever?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks: #사용할 네트워크 지정
      - forever-network
  fastapi:
    build: ./AI
    container_name: fastapi-server
    networks:
      - forever-network
    ports:
      - "8000:8000"
    env_file:
      - ./AI/.env
    restart: always

networks:
  forever-network:
