global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '4everr.2o25@gmail.com'
  smtp_auth_username: '4everr.2o25@gmail.com'
  smtp_auth_password: ${GMAIL_APP_PASSWORD}
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email-notifications'

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 'mkwak1125@gmail.com'
