name: Spring Boot CI/CD
on:
  workflow_dispatch:
  push:
    branches:
      - production
      - dev
concurrency:
  group: ${{ github.ref }}

jobs:
  call-build-workflow:
    name: 이미지 빌드
    uses: ./.github/workflows/build.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
      PROFILE: ${{ secrets.PROFILE }}

  deploy-to-production:
    needs: call-build-workflow
    if: github.ref == 'refs/heads/production'
    name: Production 서버 배포
    uses: ./.github/workflows/deploy.yml
    secrets:
      SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
      SSH_USERNAME: ${{ secrets.PROD_SSH_USERNAME }}
      SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
      SSH_PORT: ${{ secrets.PROD_SSH_PORT }}
      REPO: ${{ secrets.REPO }}
      ENVIRONMENT: prod
      WORKSPACE: ${{ secrets.PROD_WORKSPACE }}
      DEPLOY_SCRIPT: ${{ secrets.PROD_DEPLOY_SCRIPT }}

  deploy-to-dev:
    needs: call-build-workflow
    if: github.ref == 'refs/heads/dev'
    name: Dev 서버 배포
    uses: ./.github/workflows/deploy.yml
    secrets:
      SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
      SSH_USERNAME: ${{ secrets.DEV_SSH_USERNAME }}
      SSH_KEY: ${{ secrets.DEV_SSH_KEY }}
      SSH_PORT: ${{ secrets.DEV_SSH_PORT }}
      REPO: ${{ secrets.REPO }}
      ENVIRONMENT: dev
      WORKSPACE: ${{ secrets.DEV_WORKSPACE }}
      DEPLOY_SCRIPT: ${{ secrets.DEV_DEPLOY_SCRIPT }}
